### ISSUE TITLE
Is there a reason why PubMed/MEDLINE extracted list elements are joined with ";" instead of keeping them as lists ?

### ISSUE THREAD

**Issue by jtourille** [titipata/pubmed_parser#107]
First, thank you for your tool, it is very very useful.

I was wondering why there is a difference in the processing of list elements according to the parser used.
For instance:
- `parse_pubmed_xml` returns list of strings (e.g. for `author_list` and `affiliation_list`)
- `parse_medline_xml` returns concatenated lists for every list element.

Wouldn't it be more convenient to have a consistent way of handling list elements across parsers ? In that case, I would suggest to store list elements as lists instead of joining them with `;`.

Also, I could do the changes if needed.

**Comment by titipata** [comment]
Hi @jtourille, thanks for the feedback. Yes, I totally agree!

I actually have an input `author_list` parameter [here](https://github.com/titipata/pubmed_parser/blob/master/pubmed_parser/medline_parser.py#L616) and [here](https://github.com/titipata/pubmed_parser/blob/master/pubmed_parser/medline_parser.py#L616) to parse authors as a list output instead of a concatenated string. This may not be the best way and happy to take suggestions from you.

**Comment by Michael-E-Rose** [comment]
Guess by now the parameter is sufficiently documented.
